### PR TITLE
[CHILI GraFx] Storage v2

### PR DESCRIPTION
**Pull request by BramVerniest**

### CODE REVIEW

**Review by Pieterjan-Blondeel — DISMISSED** [review]

**Comment by Pieterjan-Blondeel** [comment]
@BramVerniest : I didn't 'squash & merge' yet because this shouldn't go live at this moment

**Comment by seancrowe** [comment]
@BramVerniest I pushed my reflow and set this back to draft. Feel free to edit my reflow or disregard completely.

**Comment by BramVerniest** [comment]
@seancrowe Great improvements.
@Pieterjan-Blondeel Up to you, to re-review.
Then we're good to go, when this goes live

**Review by Pieterjan-Blondeel — APPROVED** [review]

**Comment by BramVerniest** [comment]
Explain renders, labels that show what type of output count towards renders

**Comment by BramVerniest** [comment]
Add explicit description that watermarked output does not count towards renders

**Review by Pieterjan-Blondeel — APPROVED** [review]

**Pull request merged**
