### PR TITLE
Correct doc path to applications

### PR DESCRIPTION
**Pull request by tbranko**
The path structure did not conform to the current folder structure.

### CODE REVIEW

**Review by BramVerniest — COMMENTED** [review]
Hi,
Does the link not work for you?
Because the /docs/ is indeed a physical folder, but should not be needed in the link

**Comment by tbranko** [comment]
Hi Bram, 
The original URL in index.md resolves to https://github.com/chili-publish/grafx-documentation/blob/main/CHILI-GraFx/applications/overview, which returns 404, at least for me.

Compared to the correct URL:
https://github.com/chili-publish/grafx-documentation/blob/main/docs/CHILI-GraFx/applications/overview/index.md

Is the behavior different for you?
What happens when you click the "applications" link on the bottom of this page: https://github.com/chili-publish/grafx-documentation/blob/main/docs/CHILI-GraFx/index.md

**Comment by BramVerniest** [comment]
Hi @tbranko,

Thanks for the clarification.
The intention of this Repository, is to build our documentation, that ends up (after a build process) on this link
The "source code" (markdown) is build into a static website.
https://docs.chiligrafx.com/

So, we check the end-result, also with Link Checker

ANd, on that final website, I see all seems to work.

**Comment by tbranko** [comment]
Hey Bram, I will remove this pull request, I didn't know about the https://docs.chiligrafx.com

Great, I will continue reading the docs there :)
Thanks!

**Comment by BramVerniest** [comment]
Thanks for the contribution!
I learned that we need to refer to the live version, in the readme. 
To avoid confusion

**Pull request closed without merging**
